---
# Source: k8scostoptimizer/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-namespace: "default"
    meta.helm.sh/release-name: "k8s-cost-optimizer"
  labels:
    app: k8s-cost-optimizer-k8scostoptimizer
    chart: "k8scostoptimizer-v0.0.1-91404c2"
    release: "k8s-cost-optimizer"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
  name: k8s-cost-optimizer-k8scostoptimizer-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-cost-optimizer-k8scostoptimizer-role
subjects:
  - kind: ServiceAccount
    name: k8s-cost-optimizer-k8scostoptimizer
    namespace: default
