---
# Source: k8scostoptimizer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-namespace: "default"
    meta.helm.sh/release-name: "k8s-cost-optimizer"
  labels:
    app: k8s-cost-optimizer-k8scostoptimizer
    chart: "k8scostoptimizer-v0.0.1-25400a8"
    release: "k8s-cost-optimizer"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
  name: k8s-cost-optimizer-k8scostoptimizer
---
# Source: k8scostoptimizer/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-cost-optimizer-k8scostoptimizer-config
  namespace: default
data:
  config.yaml: |-
    targetNamespaces:
    []
    resourcesToIgnore:
      deployments:
      []
      statefuleSets:
      []
    specPatch:
      {}
---
# Source: k8scostoptimizer/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-namespace: "default"
    meta.helm.sh/release-name: "k8s-cost-optimizer"
  labels:
    app: k8s-cost-optimizer-k8scostoptimizer
    chart: "k8scostoptimizer-v0.0.1-25400a8"
    release: "k8s-cost-optimizer"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
  name: k8s-cost-optimizer-k8scostoptimizer-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
      - update
      - delete
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - statefulsets
    verbs:
      - list
      - get
      - update
      - patch
---
# Source: k8scostoptimizer/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-namespace: "default"
    meta.helm.sh/release-name: "k8s-cost-optimizer"
  labels:
    app: k8s-cost-optimizer-k8scostoptimizer
    chart: "k8scostoptimizer-v0.0.1-25400a8"
    release: "k8s-cost-optimizer"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
  name: k8s-cost-optimizer-k8scostoptimizer-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-cost-optimizer-k8scostoptimizer-role
subjects:
  - kind: ServiceAccount
    name: k8s-cost-optimizer-k8scostoptimizer
    namespace: default
---
# Source: k8scostoptimizer/templates/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: k8s-cost-optimizer-k8scostoptimizer
    chart: "k8scostoptimizer-v0.0.1-25400a8"
    release: "k8s-cost-optimizer"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
    group: com.stakater.platform
    provider: stakater
    version: v0.0.1-25400a8
  name: k8s-cost-optimizer-k8scostoptimizer
  namespace: default
spec:
  schedule: "*/2 * * * *"
  startingDeadlineSeconds: 200
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: k8s-cost-optimizer-k8scostoptimizer
            chart: "k8scostoptimizer-v0.0.1-25400a8"
            release: "k8s-cost-optimizer"
            heritage: "Helm"
            app.kubernetes.io/managed-by: "Helm"
            group: com.stakater.platform
            provider: stakater
            version: v0.0.1-25400a8
        spec:
          containers:
            - name: k8s-cost-optimizer-k8scostoptimizer
              image: "stakater/k8scostoptimizer:v0.0.1-25400a8"
              imagePullPolicy: IfNotPresent
              args:
              - "--config-file-path=/app/config.yaml"
              - "--patch=true"
              volumeMounts:
              - name: config
                mountPath: /app
                subPath: config.yaml
          restartPolicy: Never
          volumes:
          - name: config
            configMap:
              name: k8s-cost-optimizer-k8scostoptimizer-config
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: 
            runAsNonRoot: true
            runAsUser: 65534
          serviceAccountName: k8s-cost-optimizer-k8scostoptimizer
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
