{{- if and .Values.k8scostoptimizer.watchGlobally (.Values.k8scostoptimizer.rbac.enabled) }}
{{- if  (.Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1") }}
apiVersion: rbac.authorization.k8s.io/v1
{{ else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: ClusterRole
metadata:
  annotations:
{{ include "k8scostoptimizer-helm3.annotations" . | indent 4 }}
  labels:
{{ include "k8scostoptimizer-labels.chart" . | indent 4 }}
{{- if .Values.k8scostoptimizer.rbac.labels }}
{{ toYaml .Values.k8scostoptimizer.rbac.labels | indent 4 }}
{{- end }}
{{- if .Values.k8scostoptimizer.matchLabels }}
{{ toYaml .Values.k8scostoptimizer.matchLabels | indent 4 }}
{{- end }}
  name: {{ template "k8scostoptimizer-fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
      - update
      - delete
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - statefulsets
    verbs:
      - list
      - get
      - update
      - patch
{{- end }}
