{{- if .Values.k8scostoptimizer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
metadata:
  annotations:
{{ include "k8scostoptimizer-helm3.annotations" . | indent 4 }}
{{- if .Values.k8scostoptimizer.serviceAccount.annotations }}
{{ toYaml .Values.k8scostoptimizer.serviceAccount.annotations | indent 4 }}
{{- end }}
  labels:
{{ include "k8scostoptimizer-labels.chart" . | indent 4 }}
{{- if .Values.k8scostoptimizer.serviceAccount.labels }}
{{ toYaml .Values.k8scostoptimizer.serviceAccount.labels | indent 4 }}
{{- end }}
{{- if .Values.k8scostoptimizer.matchLabels }}
{{ toYaml .Values.k8scostoptimizer.matchLabels | indent 4 }}
{{- end }}
  name: {{ template "k8scostoptimizer-serviceAccountName" . }}
{{- end }}
